(in-package #:cl-forcats-tests)
(in-suite :cl-forcats-suite)
(test fc1-strict-creation-and-combination
  (let* ((f (fct #("b" "a" "b"))) (g (fct #("c"))))
    (is (equalp #("b" "a") (factor-levels f)))
    (is (equalp #(1 2 1 3) (factor-data (fct-c f g))))
    (is (equalp #("b" "a" "c") (lvls-union (list f g)))))
  (signals error (fct #("a" "unknown") :levels "a"))
  (let ((f (as-factor (vector nil cl-vctrs-lite:*na* t))))
    (is (equalp #("FALSE" "TRUE") (factor-levels f)))
    (is (equalp #(1 0 2) (factor-data f))))
  (let ((f (fct-cross #("a" "b") "x")))
    (is (equalp #("a:x" "b:x") (factor-levels f)))
    (is (equalp #(1 2) (factor-data f))))
  (signals error (fct-cross #("a" "b" "c") #("x" "y"))))
(test fc1-inspection-owner-preservation
  (let* ((f (make-factor #(2 0 2) :levels '("unused" "used") :ordered t))
         (unique (fct-unique f)) (counts (fct-count f :sort t :prop t)))
    (is (factor-ordered unique))
    (is (equalp #(1 2 0) (factor-data unique)))
    (is (equalp #("f" "n" "p") (cl-tibble:tbl-names counts)))
    (is (eq :factor (cl-vctrs-lite:col-type (cl-tibble:tbl-col counts "f"))))
    (is (eq :int (cl-vctrs-lite:col-type (cl-tibble:tbl-col counts "n"))))
    (is (eq :double (cl-vctrs-lite:col-type (cl-tibble:tbl-col counts "p"))))
    (is (equalp #(2 0 1) (factor-data (cl-tibble:tbl-col counts "f"))))
    (is (equalp #(2 1 0) (cl-tibble:tbl-col counts "n")))))
(test fc1-reordering-validation
  (let ((f (make-factor #(2 1 2 0) :levels '("1" "2" "3") :ordered t)))
    (is (equalp #("2" "1" "3") (factor-levels (fct-inorder f))))
    (is (factor-ordered (fct-inorder f)))
    (is (not (factor-ordered (fct-inseq f :ordered nil))))
    (is (equalp #("1" "2" "3") (factor-levels (fct-infreq f :w #(1 10 1 0)))))
    (is (equalp #(nil nil nil t) (fct-match f cl-vctrs-lite:*na*))))
  (signals error (fct-inseq (fct #("a"))))
  (signals error (fct-infreq (fct #("a")) :w #(-1))))

(test fc1-missing-level-counts-and-nan
  (let* ((f (make-factor #(0 2 1 2) :levels (vector "a" cl-vctrs-lite:*na*)))
         (counts (fct-count f :prop t)))
    (is (equalp #(1 2 1) (cl-tibble:tbl-col counts "n"))))
  (let ((p (cl-tibble:tbl-col (fct-count (make-factor #() :levels '("a")) :prop t) "p")))
    (is (eq :double (cl-vctrs-lite:col-type p)))
    #+sbcl (is (sb-ext:float-nan-p (cl-vctrs-lite:col-ref p 0))))
  (signals error (fct-infreq (fct #("a")) :w nil))
  (is (equalp #("1") (factor-levels (as-factor #(1.000000000000001d0 1.000000000000002d0)))))
)

(test fc1-numeric-levels-use-double-rounding
  (dolist (levels '(("72057594037927937" "72057594037927936")
                    ("0x100000000000001" "0x100000000000000")
                    ("0x1p-1075" "0")))
    (let ((f (make-factor #(1 2) :levels levels)))
      (is (equalp #(1 2) (factor-data (fct-inseq f)))))))
