(in-package #:cl-forcats-tests)
(in-suite :cl-forcats-suite)

(test fc3-lumping-criteria-and-ties
  (let ((f (make-factor #(1 1 1 1 1 2 3) :levels '("a" "b" "c"))))
    (is (equalp #("a" "Other") (factor-levels (fct-lump-lowfreq f))))
    (is (equalp #(1 1 1 1 1 2 2) (factor-data (fct-lump-min f 2))))
    (is (equalp #("a" "Other") (factor-levels (fct-lump-prop f (/ 1d0 7d0)))))
    (is (equalp #("b" "c" "Other") (factor-levels (fct-lump-n f -1)))))
  (let ((f (make-factor #(1 2 3) :levels '("a" "b" "c"))))
    (is (equalp #("a" "b" "c") (factor-levels (fct-lump-n f 1))))
    (is (equalp #("a" "Other") (factor-levels (fct-lump-n f 1 :ties-method "first"))))
    (is (equalp #("c" "Other") (factor-levels (fct-lump-n f 1 :ties-method "last"))))
    (signals error (fct-lump-n f 1 :w nil))))

(test fc3-missing-level-conversion
  (let* ((f (make-factor #(0 2 1 2) :levels (vector "a" cl-vctrs-lite:*na*) :ordered t))
         (out (fct-na-level-to-value f)))
    (setf (cl-vctrs-lite:col-names f) #( "implicit" "explicit" "a" "explicit"))
    (is (equalp #(0 0 1 0) (factor-data out)))
    (is (equalp #("a") (factor-levels out)))
    (is (factor-ordered out))
    (is (equalp #(2 2 1 2) (factor-data (fct-na-value-to-level f))))
    (is (equalp (cl-vctrs-lite:col-names f) (cl-vctrs-lite:col-names (fct-na-value-to-level f))))
    (is (equalp #(1 1 1 1) (factor-data (fct-na-value-to-level f :level "a")))))
  (is (= 1 (length (factor-levels (fct-na-value-to-level (make-factor #() :levels nil))))))
  (signals error (fct-na-level-to-value (make-factor #() :levels nil) :extra-levels nil)))

(test fc3-overflow-weights-and-fractional-insertion
  (let ((f (make-factor #(1 1 2) :levels '("a" "b" "unused"))))
    (is (equalp #("a" "Other") (factor-levels (fct-lump-n f 1 :w #(1d308 1d308 1d0)))))
    (is (equalp #("a" "b" "Other") (factor-levels (fct-lump-min f 1 :w #(1d308 1d308 1d0)))))
    (let ((out (fct-lump-prop f 0.1d0 :w #(1d308 1d308 1d0))))
      (is (cl-vctrs-lite:na-p (aref (factor-levels out) 0)))
      (is (equalp #(1 1 2) (factor-data out))))
    (signals error (fct-lump-lowfreq f :w #(1d308 1d308 1d0))))
  (signals error (fct-expand (make-factor #(1 2 3) :levels '("a" "b" "c")) "d" :after 1.5d0)))

(test fc3-pinned-random-ties-and-name-owner
  (let ((f (make-factor #(2 1 0 2 3 1 4) :levels '("a" "b" "c" "d" "unused") :ordered t))
        (stream (make-random-state t)))
    (setf (cl-vctrs-lite:col-names f) (vector "b" "a" cl-vctrs-lite:*na* "b" "c" "a" "d"))
    (let ((control (make-random-state stream)) (out (fct-lump-n f 1 :ties-method "random" :seed 0 :random-state stream)))
      (is (equalp #("b" "Other") (factor-levels out)))
      (is (equalp #(1 2 0 1 2 2 2) (factor-data out)))
      (is (equalp (cl-vctrs-lite:col-names f) (cl-vctrs-lite:col-names out)))
      (is (factor-ordered out))
      (is (= (random 10000 control) (random 10000 stream))))
    (is (equalp #(2 1 3 2 3 1 3) (factor-data (fct-lump-n f 2 :other-level cl-vctrs-lite:*na*))))))
